overrides:
  "@iconify/utils": 3.1.0
  "@isaacs/brace-expansion@<6": 5.0.1
  flatted: ^3.4.2
  h3: ^1.15.9
  koa: ^2.16.4
  "minimatch@>=3 <4": 3.1.4
  "minimatch@>=5 <6": 5.1.8
  "minimatch@>=9 <10": 9.0.7
  "minimatch@>=10 <11": 10.2.3
  node-forge: ^1.4.0
  "picomatch@<3": 2.3.2
  "picomatch@>=4 <5": 4.0.4
  rollup: ^4.59.0
  serialize-javascript: ^7.0.5
  svgo: ^4.0.1
  tar: ^7.5.11
  "brace-expansion@<2": 1.1.13
  "brace-expansion@>=2 <3": 2.0.3
  unhead: 2.1.12
  yaml: ^2.8.3
  ajv: ^6.14.0

patchedDependencies:
  nitropack@2.13.1: patches/nitropack@2.13.1.patch

allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
